### ISSUE TITLE
Error with the date command

### ISSUE THREAD

**Issue by adrianbrink** [BillSkiCO/RX-Modulator#5]
macOS 10.12
deps installed
executing date works

Error msg:
```
usage: date [-jnRu] [-d dst] [-r seconds] [-t west] [-v[+|-]val[ymwdHMS]] ...
            [-f fmt date | [[[mm]dd]HH]MM[[cc]yy][.ss]] [+format]
```
After selecting a date in the date picker.

What could be the issue?

**Comment by BillSkiCO** [comment]
The spacing may be wrong when you copy and pasted it?

Does this work?
`
$ date -d "00:00" +%s
`

**Comment by adrianbrink** [comment]
`date -d "00:00" +%s` doesn't work.

```
➜  lol_store git:(master) date -d "00:00" +%s
usage: date [-jnRu] [-d dst] [-r seconds] [-t west] [-v[+|-]val[ymwdHMS]] ...
            [-f fmt date | [[[mm]dd]HH]MM[[cc]yy][.ss]] [+format]
```

**Comment by BillSkiCO** [comment]
After reading the OSX [man ](https://developer.apple.com/legacy/library/documentation/Darwin/Reference/ManPages/man1/date.1.html)page I've figured out your problem. OSX has a different way of defining the date utility: ``date -j -f "%a %b %d %T %Z %Y" "`date`" "+%s"`` might be the solution for that first call to today's date.

I'll have to implement an `$os` check before the date command so that it is formatted properly. Thanks for pointing this compatibility issue out!

You could always try to reinstall `coreutils` and change references to `gdate`.

### (Re)install coreutils

1. Press `Command+Space` and type **_Terminal_** and press **_enter/return_** key.

2. Run in Terminal:
`ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)" < /dev/null 2> /dev/null`
and press **_enter/return_** key. Wait for the command to finish.

3. Run:
`brew install coreutils`

**Comment by BillSkiCO** [comment]
Fixed. Should work with Linux and Darwin now

**Comment by adrianbrink** [comment]
Cool :)

**Comment by tsheaff** [comment]
For posterity: `brew install coreutils` fixed this for me!

**Comment by unaware-puffin** [comment]
For double posterity: remember to set your PATH per homebrew instructions.
add a "gnubin" directory to your PATH from your bashrc like:
PATH="/usr/local/opt/coreutils/libexec/gnubin:$PATH"

**Comment by joriewong** [comment]
it's not worked on MacOS.
`date +%s -d '20210720'`
